import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { onnx } from 'onnx-proto';

const { FLOAT, INT32, INT64 } = onnx.TensorProto.DataType;

function value(name: string, elemType: number, dims: (number | string)[]): onnx.IValueInfoProto {
  return {
    name,
    type: {
      tensorType: {
        elemType,
        shape: {
          dim: dims.map((d) => (typeof d === 'string' ? { dimParam: d } : { dimValue: d })),
        },
      },
    },
  };
}

function encode(graph: onnx.IGraphProto): Uint8Array {
  const model: onnx.IModelProto = {
    irVersion: 8,
    producerName: 'di-ml-test-fixtures',
    opsetImport: [{ domain: '', version: 17 }],
    graph,
  };
  const error = onnx.ModelProto.verify(model);
  if (error) throw new Error(error);
  return onnx.ModelProto.encode(model).finish();
}

/** Deterministic test graphs, generated by Bun before the Session tests run. */
export async function generateInferenceFixtures(directory: string) {
  const xor = encode({
    name: 'xor_mlp',
    input: [value('input', FLOAT, ['N', 2])],
    output: [value('output', FLOAT, ['N', 1])],
    node: [
      { opType: 'Gemm', input: ['input', 'W1', 'B1'], output: ['h1'] },
      { opType: 'Relu', input: ['h1'], output: ['h2'] },
      { opType: 'Gemm', input: ['h2', 'W2', 'B2'], output: ['logits'] },
      { opType: 'Sigmoid', input: ['logits'], output: ['output'] },
    ],
    // Fixed weights: the first two hidden units compute relu(x-y) and relu(y-x).
    // This is an inference fixture, independent of the Rust training tests.
    initializer: [
      {
        name: 'W1',
        dataType: FLOAT,
        dims: [2, 8],
        floatData: [1, -1, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0],
      },
      { name: 'B1', dataType: FLOAT, dims: [8], floatData: Array(8).fill(0) },
      { name: 'W2', dataType: FLOAT, dims: [8, 1], floatData: [12, 12, 0, 0, 0, 0, 0, 0] },
      { name: 'B2', dataType: FLOAT, dims: [1], floatData: [-6] },
    ],
  });
  const integer = encode({
    name: 'integer_tensors',
    input: [value('ids', INT64, [2]), value('mask', INT32, [2]), value('large', INT64, [1])],
    output: [
      value('embedding', FLOAT, [2, 2]),
      value('mask_out', INT32, [2]),
      value('large_out', INT64, [1]),
    ],
    node: [
      { opType: 'Gather', input: ['table', 'ids'], output: ['embedding'] },
      { opType: 'Identity', input: ['mask'], output: ['mask_out'] },
      { opType: 'Identity', input: ['large'], output: ['large_out'] },
    ],
    initializer: [{ name: 'table', dataType: FLOAT, dims: [3, 2], floatData: [1, 2, 3, 4, 5, 6] }],
  });
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, 'xor.onnx'), xor);
  await writeFile(join(directory, 'integer.onnx'), integer);
}
